# Generated by Django 4.0 on 2022-02-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('field', models.CharField(default='', max_length=100)),
                ('iid', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
